project_id = "whjmbsiwhfgdffatajzx"

[functions.analyze-emotion]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.generate-emotion-art]
verify_jwt = false

[functions.detect-mental-health-risk]
verify_jwt = false
